[book]
authors = ["Daehyun Kim"]
language = "en"
multilingual = false
src = "src"
title = "Cubvec Plan"

[output.html]
default-theme = "light"
preferred-dark-theme = "light"
smart-punctuation = true
mathjax-support = false
copy-fonts = true
no-section-label = false
[output.html.fold]
enable = false
